version: 2.1
orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.2.0
jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies..."
          npm install
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm run test

workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
  
  build-docker-image-only:
    jobs:
      - docker/publish:
          image: bowlofowls/m4
          update-description: true
  build-docker-image-only-with-buildkit:
    jobs:
      - docker/publish:
          image: bowlofowls/m4
          remote-docker-version: 20.10.12
          update-description: true
          use-buildkit: true
          use-remote-docker: true
